#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'build-branch',
 'build_date': '2013-10-05 22:57:34 +0200',
 'clean': False,
 'date': '2013-10-05 22:49:46 +0200',
 'revision_id': 'tca@gnu.org-20131005204946-k0k0e5z23bk8lqfp',
 'revno': '2140'}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print 'revision: %(revno)s' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
